services:
  hackapay-pagamento:
    image: 'hackapay-pagamento-docker-image'
    build:
      context: .
    container_name: 'hackapay-pagamento-docker-container'
    depends_on:
      - db
    ports:
      - "8083:8083"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/hackapay-pagamento-db
      - SPRING_DATASOURCE_USERNAME=hackaPay
      - SPRING_DATASOURCE_PASSWORD=hackaPayPagamento
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create-drop
    networks:
      - hackapay-network
  db:
    image: postgres:latest
    container_name: hackapay-pagamento-db
    command: -p 5432
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=hackaPay
      - POSTGRES_PASSWORD=hackaPayPagamento
      - POSTGRES_DB=hackapay-pagamento-db
    networks:
      - hackapay-network
networks:
  hackapay-network:
    external: true